[package]
name = "aocf"
version = "0.1.0"
authors = ["Ed Cragg <drq.11235@gmail.com>"]
edition = "2018"
license = "ISC"
readme = "README.md"
description = "A crate and CLI helper tool for Advent of Code"
repository = "https://github.com/nuxeh/aocf"

[dependencies]
failure = "0.1.6"
html2md = "0.2.9"
regex = "1.3.3"
reqwest = {version = "0.10.1", features = ["blocking"]}
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
