[package]
name = "aocf_cli"
version = "0.1.0"
authors = ["Ed Cragg <drq.11235@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tempfile = "*"

[dependencies]
aocf = {version = "*", path = ".."}
chrono = "0.4.10"
docopt = "1.1.0"
failure = "0.1.6"
log = "0.4.8"
serde = "1.0.103"
serde_derive = "1.0.103"
slog = "2.5.2"
toml = "0.5.5"
